### ISSUE TITLE
[Experimental] rolling-update Updater

### ISSUE THREAD

**Issue by sr229** [Monika-After-Story/MonikaModDev#1466]
This serves as the current copy of the roadmap for [Vera](https://github.com/ProjectMonika/Vera), a planned replacement to the current updater for MAS.

### Current working group

- @sr229 (Project Leader, ServOps)
- @wafflemelon (Developer) 

### TODOs:

- [ ] Backwards compatibility with Python 2.7 (Required since RenPy is Py2)
- [ ] Follow "Always-Overwrite" strategy for updates.
- [ ] UI Improvements.
- [ ] Non-blocking updates.

**Comment by ThePotatoGuy** [comment]
> Vera performs a background update and searches for a new version every hour. 

Please change this to once per 24 hours. My wallet does not agree with frequent update checking.
