### ISSUE TITLE
More affection-dependent greetings / farewells

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#2644]
if your affection is low, monika's greetings / farewells are out of place.

We should have more variety of greetings / farewells that only appear at certain affection levels.

## TODO:
- [x] ensure greetings / farewell frameworks can use affection rules when filtering

### broken
- [x] add more greetings
- [x] add more farewells

### distressed
- [x] add more greetings
- [x] add more farewells

### upset
- [x] add more greetings
- [x] add more farewells

Happier affections tbd
