### ISSUE TITLE
JSONify sprite objects

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#3416]
Piano could be JSON'd because it consists of PianoNoteMatch objects that could be represented in JSON notation.

Sprites are objects that also could be written as JSONs, so might as well make that open so people can drop their own outfits/hair/acs into MAS.

Progpoints are handled via the standard form.

Overrides are not considered atm. I think we will be using the exprop system to drive override-like functionality.

At the start, we will be writing most of the prog points initially.

Tasklist:
- [x] standardize JSON format for `MASAccessory`
- [x] standardize JSON format for `MASHair`
- [x] standardize JSON format for `MASClothes`
- [x] standardize JSON format for acs selectable
- [x] standardize JSON format for hair selectable
- [x] standardize JSON format for clothes selectable
- [x] add docking station for sprite object JSONs
- [x] add JSON loading for `MASPoseMap`
- [x] MASPoseMap unit tests
- [x] JSON testcases for hair
- [x] ignore keys that start with `__`
- [x] Test label to execute progpoints for testing
- [x] delayed hair verification and handling
- [x] giftname processing -> putting the maps into the appropriate per dicts
- [ ] ~~witch hat json~~ on hold until leaning versions exist
- [ ] ~~neko ears json~~ on hold until leaning versions exist
- [x] cherry hair clip json #4087 
- [x] heart hair clip json #4087 
- [x] emerald 8th hair clip json #4087 
- [ ] cute hair ribbon json #4087

**Comment by ThePotatoGuy** [comment]
[keeping open as reminder to myself]

**Comment by ThePotatoGuy** [comment]
for prog points, could have it just assume names via a standard form:
```python
_<sprite object type>_<id>_entry
_<sprite object type>_<id>_exit
```

so a new accessory with id `custom_thing` will be:
```python
_acs_custom_thing_entry
_acs_custom_thing_exit
```

clothes:
```python
_clothes_custom_thing_entry
_clothes_custom_thing_exit
```

hair:
```python
_hair_custom_thing_entry
_hair_custom_thing_exit
```

could make the ID thing overridable.
also could enforce that the id must use valid chars (no `-`)

**Comment by ThePotatoGuy** [comment]
[ok will start this now]

**Comment by ThePotatoGuy** [comment]
checklist updated

**Comment by ThePotatoGuy** [comment]
[closing this as complete]
