### ISSUE TITLE
RPS (janken)

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#6700]
primary thread for tracking rps dev

# TODO
- [ ] add images from #6680
- [ ] create basic gameplay (being able to select a choice, have monika make choice, and show result)
- [ ] add game to game framework
- [ ] add better AI

# previous issues
#55 #762 #6680

**Comment by Rai99** [comment]
What I was thinking is that on top of randomly picking one of the three options, we could keep track of the last X player moves, probably 7, and based on that data, have a chance to pick what's most likely to beat the player's next move. 

So there would be a chance to pick randomly, and a chance to base off of the past few moves, maybe 50/50, or 40/60, something along those lines. 

The idea is for Monika to recognize if you favor a specific move, or if you just spam the same move over and over, so you're less likely to win if you do. 

Maybe the chance for random or going off of past moves should be based on how good of an estimate she has based on your past moves, so like if you switch it up with no pattern, she's more likely to just go randomly, but if you have a lot of the same move, she's more likely to pick what beats that.

**Comment by Rai99** [comment]
Assuming the log or whatever is completely filled with the same move, it should probably take 3 or 4 different moves to turn the tides away from deciding it's just spamming the same move. 

This would probably be looked into and maybe refined further with how many moves we decide to keep track of, etc.

**Comment by YoraeRasante** [comment]
I remember janken being a plot competition on Hunter x Hunter, pretty early in it. Been a while, but if I remember right...

- Most people instinctivelly start with rock.
- Right after losing they tend to use the hand that would have won their last bout.

Plus, as Rai99 mentioned, people have their personal preference, even if they don't notice but that someone that plays with them enough can plan for.  Mine is scissors, for example.

So to me they could take effect in three changes on the rng:

- If first janken play of the day, Monika has 1/5 chance to use Rock,
- If she lost the previous game, Monika has 1/5 chance to use the one that would have won (if she lost to Rock, chance is of using Paper)
- Assuming neither of the previous checks were the ones to go, 1/4 chance to use her personal favorite (I imagine it as Paper).
- If getting to this point, use Rai99's idea of a pool to check chances of player choosing their favorite, I imagine 1/3 of chance of using that pool.
- Actual random chance.

Chances were an example out of my head, but I _do_ have a reasoning for them.
The 1/5 ones are instinctive, but as she is aware she can try to control them.
The 1/4 one is for it being a _personal_ instinct, meaning harder to control but still possible.
The 1/3 one is  because as much as we used it more, there is also a chance we would not to so. I was thinking 1/2 instead but thought too certain then.
